"""Public, framework-independent domain contracts."""

from .baseline import (
    AbstentionReason,
    BaselineAbstention,
    BaselinePolicy,
    BaselineRanking,
    BaselineResult,
    SignalBaselineInput,
    SignalEvaluation,
    SuspicionCandidate,
    rank_metric_shifts,
)
from .change_evidence import (
    SCHEMA_VERSION as CHANGE_EVIDENCE_SCHEMA_VERSION,
)
from .change_evidence import (
    ChangeEventEvidence,
    ChangeEventLedger,
    ChangePhase,
    compile_change_event_ledger,
    validate_change_event_ledger,
)
from .change_hypotheses import (
    MAX_CHANGE_PREDICATES,
    ChangeCooccurrencePredicate,
    ChangeHypothesisDocument,
    ChangePhaseConstraint,
    validate_change_hypothesis_document,
)
from .change_verifier import (
    ChangeHypothesisVerificationResult,
    ChangePredicateVerificationResult,
    ChangeUnknownReason,
    verify_change_hypothesis,
)
from .changes import (
    MAX_CHANGE_EVENTS,
    ChangeEvent,
    ChangeEventKey,
    ChangeEventLog,
    ChangeKind,
)
from .errors import (
    BaselineComputationError,
    CanonicalSerializationError,
    DomainError,
    DomainValidationError,
    DuplicateSignalError,
    InvalidBaselineConfigurationError,
    InvalidChangeEventError,
    InvalidChangeEventLedgerError,
    InvalidChangeHypothesisError,
    InvalidEvidenceLedgerError,
    InvalidHypothesisError,
    InvalidIdentifierError,
    InvalidIncidentWindowError,
    InvalidMetricPointError,
    InvalidMetricSignalError,
    InvalidTimestampError,
)
from .evidence import (
    SCHEMA_VERSION as EVIDENCE_SCHEMA_VERSION,
)
from .evidence import (
    MetricEvidenceLedger,
    MetricShiftDecision,
    MetricShiftDecisionKind,
    MetricShiftEvidence,
    compile_metric_shift_ledger,
    validate_metric_evidence_ledger,
)
from .hypotheses import (
    MAX_PREDICATES,
    ExpectedDirection,
    HypothesisComposition,
    HypothesisDocument,
    HypothesisSemantics,
    MetricShiftPredicate,
    validate_hypothesis_document,
)
from .identifiers import CaseId, EvidenceId, IncidentId, RunId, TenantId
from .incidents import IncidentWindow
from .metrics import MetricPoint, MetricSignal, SignalKey
from .serialization import (
    BASELINE_RANKING_SCHEMA_VERSION,
    CHANGE_VERIFICATION_SCHEMA_VERSION,
    VERIFICATION_SCHEMA_VERSION,
    baseline_ranking_json,
    change_ledger_json,
    change_verification_json,
    ledger_json,
    metric_evidence_entry_json,
    verification_json,
)
from .verifier import (
    HypothesisVerificationResult,
    ObservedDirection,
    PredicateVerificationResult,
    UnknownReason,
    VerificationReason,
    VerificationVerdict,
    verify_hypothesis,
)

__all__ = [
    "BASELINE_RANKING_SCHEMA_VERSION",
    "CHANGE_EVIDENCE_SCHEMA_VERSION",
    "CHANGE_VERIFICATION_SCHEMA_VERSION",
    "EVIDENCE_SCHEMA_VERSION",
    "MAX_CHANGE_EVENTS",
    "MAX_CHANGE_PREDICATES",
    "MAX_PREDICATES",
    "VERIFICATION_SCHEMA_VERSION",
    "AbstentionReason",
    "BaselineAbstention",
    "BaselineComputationError",
    "BaselinePolicy",
    "BaselineRanking",
    "BaselineResult",
    "CanonicalSerializationError",
    "CaseId",
    "ChangeCooccurrencePredicate",
    "ChangeEvent",
    "ChangeEventEvidence",
    "ChangeEventKey",
    "ChangeEventLedger",
    "ChangeEventLog",
    "ChangeHypothesisDocument",
    "ChangeHypothesisVerificationResult",
    "ChangeKind",
    "ChangePhase",
    "ChangePhaseConstraint",
    "ChangePredicateVerificationResult",
    "ChangeUnknownReason",
    "DomainError",
    "DomainValidationError",
    "DuplicateSignalError",
    "EvidenceId",
    "ExpectedDirection",
    "HypothesisComposition",
    "HypothesisDocument",
    "HypothesisSemantics",
    "HypothesisVerificationResult",
    "IncidentId",
    "IncidentWindow",
    "InvalidBaselineConfigurationError",
    "InvalidChangeEventError",
    "InvalidChangeEventLedgerError",
    "InvalidChangeHypothesisError",
    "InvalidEvidenceLedgerError",
    "InvalidHypothesisError",
    "InvalidIdentifierError",
    "InvalidIncidentWindowError",
    "InvalidMetricPointError",
    "InvalidMetricSignalError",
    "InvalidTimestampError",
    "MetricEvidenceLedger",
    "MetricPoint",
    "MetricShiftDecision",
    "MetricShiftDecisionKind",
    "MetricShiftEvidence",
    "MetricShiftPredicate",
    "MetricSignal",
    "ObservedDirection",
    "PredicateVerificationResult",
    "RunId",
    "SignalBaselineInput",
    "SignalEvaluation",
    "SignalKey",
    "SuspicionCandidate",
    "TenantId",
    "UnknownReason",
    "VerificationReason",
    "VerificationVerdict",
    "baseline_ranking_json",
    "change_ledger_json",
    "change_verification_json",
    "compile_change_event_ledger",
    "compile_metric_shift_ledger",
    "ledger_json",
    "metric_evidence_entry_json",
    "rank_metric_shifts",
    "validate_change_event_ledger",
    "validate_change_hypothesis_document",
    "validate_hypothesis_document",
    "validate_metric_evidence_ledger",
    "verification_json",
    "verify_change_hypothesis",
    "verify_hypothesis",
]
