"""Public, framework-independent domain contracts."""

from .baseline import (
    AbstentionReason,
    BaselineAbstention,
    BaselinePolicy,
    BaselineRanking,
    BaselineResult,
    SignalBaselineInput,
    SignalEvaluation,
    SuspicionCandidate,
    rank_metric_shifts,
)
from .errors import (
    BaselineComputationError,
    CanonicalSerializationError,
    DomainError,
    DomainValidationError,
    DuplicateSignalError,
    InvalidBaselineConfigurationError,
    InvalidEvidenceLedgerError,
    InvalidHypothesisError,
    InvalidIdentifierError,
    InvalidIncidentWindowError,
    InvalidMetricPointError,
    InvalidMetricSignalError,
    InvalidTimestampError,
)
from .evidence import (
    SCHEMA_VERSION as EVIDENCE_SCHEMA_VERSION,
)
from .evidence import (
    MetricEvidenceLedger,
    MetricShiftDecision,
    MetricShiftDecisionKind,
    MetricShiftEvidence,
    compile_metric_shift_ledger,
    validate_metric_evidence_ledger,
)
from .hypotheses import (
    MAX_PREDICATES,
    ExpectedDirection,
    HypothesisComposition,
    HypothesisDocument,
    HypothesisSemantics,
    MetricShiftPredicate,
    validate_hypothesis_document,
)
from .identifiers import CaseId, EvidenceId, IncidentId, RunId, TenantId
from .incidents import IncidentWindow
from .metrics import MetricPoint, MetricSignal, SignalKey
from .serialization import VERIFICATION_SCHEMA_VERSION, ledger_json, verification_json
from .verifier import (
    HypothesisVerificationResult,
    ObservedDirection,
    PredicateVerificationResult,
    UnknownReason,
    VerificationReason,
    VerificationVerdict,
    verify_hypothesis,
)

__all__ = [
    "EVIDENCE_SCHEMA_VERSION",
    "MAX_PREDICATES",
    "VERIFICATION_SCHEMA_VERSION",
    "AbstentionReason",
    "BaselineAbstention",
    "BaselineComputationError",
    "BaselinePolicy",
    "BaselineRanking",
    "BaselineResult",
    "CanonicalSerializationError",
    "CaseId",
    "DomainError",
    "DomainValidationError",
    "DuplicateSignalError",
    "EvidenceId",
    "ExpectedDirection",
    "HypothesisComposition",
    "HypothesisDocument",
    "HypothesisSemantics",
    "HypothesisVerificationResult",
    "IncidentId",
    "IncidentWindow",
    "InvalidBaselineConfigurationError",
    "InvalidEvidenceLedgerError",
    "InvalidHypothesisError",
    "InvalidIdentifierError",
    "InvalidIncidentWindowError",
    "InvalidMetricPointError",
    "InvalidMetricSignalError",
    "InvalidTimestampError",
    "MetricEvidenceLedger",
    "MetricPoint",
    "MetricShiftDecision",
    "MetricShiftDecisionKind",
    "MetricShiftEvidence",
    "MetricShiftPredicate",
    "MetricSignal",
    "ObservedDirection",
    "PredicateVerificationResult",
    "RunId",
    "SignalBaselineInput",
    "SignalEvaluation",
    "SignalKey",
    "SuspicionCandidate",
    "TenantId",
    "UnknownReason",
    "VerificationReason",
    "VerificationVerdict",
    "compile_metric_shift_ledger",
    "ledger_json",
    "rank_metric_shifts",
    "validate_hypothesis_document",
    "validate_metric_evidence_ledger",
    "verification_json",
    "verify_hypothesis",
]
